### ISSUE TITLE
Removing/change fluid grid padding

### ISSUE THREAD

**Issue by joelinteman** [roylee0704/react-flexbox-grid#127]
Hi, is there a way to remove/change the default padding of 2rem of the .flexboxgrid__container-fluid?

**Comment by velykov** [comment]
I think no

**Comment by yougotashovel** [comment]
Has anyone found a solution to this?

**Comment by joelinteman** [comment]
Use CSS grid. :)

**Comment by yougotashovel** [comment]
That's where i started, and why i came to this package.
CSS grid doesn't work in enough browsers to solely rely on it yet, especially in projects where column layout is important, and target audience is using older browser versions.

caniuse.com says it's supported most places, but testing on devices/browsers shows otherwise.
A large enough percentage of people aren't running the latest versions of some browsers, especially safari.

Ended up building my own react flexbox grid with glamorous.
