### ISSUE TITLE
16 column grid

### ISSUE THREAD

**Issue by og2t** [roylee0704/react-flexbox-grid#56]
Would it be possible to change the number of columns to 16?

**Comment by mrsufgi** [comment]
the grid system is based entirely on flexboxgrid.css, since this library is depended on the original flexboxgrid package you can only fork this repo and require your own compiled 16 cols css file. 

if you want to compile a custom grid you can only use the scss fork for flexboxgrid.css since the original one don't and won't support less/scss

**Comment by djensen47** [comment]
It would be really nice to be able to be able to bring your own flexboxgrid css. That we folks could overwrite details like the number of columns. 

Based on where the flexboxgrid project seems to be going, it might be necessary to support this somehow.

**Comment by mrsufgi** [comment]
Maybe the best solution is to simply use flexboxgrid sass fork and bind props to its variables. This pipeline can offer more flexibility. 

Just my 2 cents :) 
I'll probably start working on this in the near future and submit a PR.

**Comment by djensen47** [comment]
I've done something like this but without a fork. 

-  install `react-flexbox-grid`
- do not install `flexboxgrid`
- install `flexboxgrid-sass`
- in the root of your project create a file `flexboxgrid.scss` that overwrites the settings and includes the sass like this:
```
$grid-columns: 12;

$gutter-width: 1em;
$outer-margin: 1em;

$breakpoints:
  sm 38rem 38rem,
  md 52rem 52rem,
  lg 80rem 78rem,
  xl 120rem 116rem;

@import "~flexboxgrid-sass/flexboxgrid.scss";
```
- Now when `react-flexbox-grid` does `import style from 'flexboxgrid';` it should look to the file in your local project instead of the one in the node_modules, because it does not exist

**Comment by silvenon** [comment]
react-flexbox-grid is strictly meant to be React bindings for flexboxgrid, not fix its shortcomings. flexboxgrid doesn't allow such customization.
