### ISSUE TITLE
typescript definition

### ISSUE THREAD

**Issue by MichaelBitard** [roylee0704/react-flexbox-grid#62]
Is there someone working on typescript definitions?

**Comment by delaneyj** [comment]
```ts
declare module "react-flexbox-grid" {
  interface ColProps extends React.Props<Col> {
    xs?: number|boolean;
    sm?: number|boolean;
    md?: number|boolean;
    lg?: number|boolean;
    xsOffset?: number;
    smOffset?: number;
    mdOffset?: number;
    lgOffset?: number;
    reverse?: boolean;
    className?: string;
    tagName?: string;
    children?: React.ReactNode;
  }

  export class Col extends React.Component<ColProps, {}> {
  }

  interface GridProps extends React.Props<Grid> {
    fluid?: boolean;
    className?: string;
    tagName?: string;
    children?: React.ReactNode;
  }

  export class Grid extends React.Component<GridProps, {}> {
  }

  interface RowProps extends React.Props<Row> {
    reverse?: boolean;
    start?: string;
    center?: string;
    end?: string;
    top?: string;
    middle?: string;
    bottom?: string;
    around?: string;
    between?: string;
    first?: string;
    last?: string;
    className?: string;
    tagName?: string;
    children?: React.ReactNode;
  }

  export class Row extends React.Component<RowProps, {}> {
  }
}
```

seems to work for me so far but its be great if it was included in the source as `index.d.ts`.  If this works for you thing we can try to get a pull request merged.

**Comment by Oduig** [comment]
Hi there. I have a setup with Typescript, React and Webpack, but I can't get it to work with react-flexbox-grid.

tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES6",
    "jsx": "react",
    "module": "commonjs",
    "sourceMap": true,
    "noImplicitAny": true,
    "experimentalDecorators": true,
    "typeRoots" : ["./typings"]
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```

In the folder `typings`, I have a file called `ReactFlexboxGrid.d.ts` with the contents as above.
In the file `MyComponent.tsx`, I import the library: 
`import {Grid, Col, Row} from 'react-flexbox-grid';`

When I run `tsc`, I get the following error:
`error TS2307: Cannot find module 'react-flexbox-grid'.`
The same thing happens if I try to use a deeper path, e.g. `react-flexbox-grid/libs/components/Grid`

I'm new to typescript and the combination of 4 technologies makes the problem very hard to google for. Any idea what's going wrong here?

**Comment by IRus** [comment]
@Oduig since my PR will be merged, you can use typescript with this package without hacks from SO answer.

**Comment by Oduig** [comment]
@IRus Thanks for your contribution. For what it's worth, I can attest that the typings file works as it should! ;)

**Comment by silvenon** [comment]
#74 has been merged, so I'm closing this. After we merge #90 and a bit of manual testing I'll hopefully get @roylee0704 to publish a release.
