### ISSUE TITLE
Strange issue when setting 0 margin to body

### ISSUE THREAD

**Issue by DanielRamosAcosta** [roylee0704/react-flexbox-grid#79]
I have a demo of the issue in [this repo](https://github.com/DanielRamosAcosta/react-flexbox-grid-bug). The issue is that when I'm setting the [body margin to 0](https://github.com/DanielRamosAcosta/react-flexbox-grid-bug/blob/master/app/index.tpl.html#L9), when visualizing it on mobile devices (for example iPhone 5) I'm getting an horizontal scrollbar. I've deployed it on [gh-pages](https://danielramosacosta.github.io/react-flexbox-grid-bug) so you can try it.

**Comment by michelalbers** [comment]
+1

**Comment by Palsson123** [comment]
I have the exact same problem, my row gets 16 px to wide, the same as your.

**Comment by Palsson123** [comment]
It seems that it is fixed when i put my rows and cols inside a <Grid fluid> component.

**Comment by silvenon** [comment]
Yes, like in the example provided in the [docs](https://github.com/roylee0704/react-flexbox-grid/blob/master/README.md#code-snippets), you should wrap your app in `<Grid>`, because `<Row>` uses negative margin to make up for the extra space at the beginning and end, which resulted from `<Col>` always having both left and right padding. This is a common practice used in many grid systems. When you set `margin: 0`, `<body>` overflowed, that's why the scrollbar appeared.

Let me know if you have more questions about this. 😉
